services:
  build-image:
    image: cpp-on-avr
    command: bash -c "echo build-image completed."
    build: .
  build-hex:
    image: cpp-on-avr
    command: bash -c "cmake -DCMAKE_TOOLCHAIN_FILE="avr.cmake" -B Build/Avr && cmake --build Build/Avr --target app size hex"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  unit-tests:
    image: cpp-on-avr
    command: bash -c "cmake -B Build/Host && cmake --build Build/Host --target hello_test && ctest --test-dir Build/Host/Tests"
    depends_on:
    - build-image
    volumes:
    - ./:/app
