name: Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: determine short GIT hash
        id:   vars
        run:  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build docker image
        run:  docker compose build
      - name: build hex file
        run:  docker compose run --rm build-hex
      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-${{ steps.vars.outputs.sha_short }}
          path: Build/Avr/app.hex
          if-no-files-found: error
          retention-days: 5
      - name: run unit tests
        run:  docker compose run --rm unit-tests
